### ISSUE TITLE
Compare URL showing on non-download pages

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/edd-compare-products#2]
Probably because I'm stupid and didn't add the same condition I'm using to enqueue as I am to add the URL.

**Comment by d4mation** [comment]
Do you remember which pages it was appearing on? 

I may have fixed this issue unintentionally in 3597f76

**Comment by brashrebel** [comment]
I don't recall exactly. I think the URL gets put in the DOM somewhere and I came across some page or pages where it was there. Maybe cart or checkout pages? Account pages? I don't really remember.

**Comment by d4mation** [comment]
Ah, you're talking about the URL itself in the hidden `<div>`? I was thinking it was added buttons.

I just placed the same conditional in there that I've got for the JavaScript enqueues. Now it should only appear when we've got the JavaScript to handle it.
